---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tinysyslog
  labels:
    component: tinysyslog
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      component: tinysyslog
  template:
    metadata:
      labels:
        component: tinysyslog
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - image: admiralobvious/tinysyslog:latest
        name: tinysyslog
        imagePullPolicy: Always
        ports:
        - name: syslog-tcp
          containerPort: 5140
        - name: syslog-udp
          containerPort: 5140
          protocol: UDP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: tinysyslog
  labels:
    component: tinysyslog
spec:
  ports:
  - name: syslog-tcp
    port: 5140
  - name: syslog-udp
    protocol: UDP
    port: 5140
  selector:
    component: tinysyslog
