name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  unit:
    strategy:
      matrix:
        go-version: [ '1.23.x', '1.24.x' ]
        os: [  macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: go run gotest.tools/gotestsum@latest -f testname -- ./... -race -count=1 -coverprofile=coverage.txt -covermode=atomic -shuffle=on

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.go-version == '1.23.x' }}
        uses: codecov/codecov-action@v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
